# Build Stage
FROM node:20-alpine AS build

WORKDIR /app

# Add build argument for API URL
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ARG VITE_POLAR_STARTUP_PRODUCT_ID
ENV VITE_POLAR_STARTUP_PRODUCT_ID=$VITE_POLAR_STARTUP_PRODUCT_ID
ARG VITE_POLAR_STARTUP_ANNUAL_PRODUCT_ID
ENV VITE_POLAR_STARTUP_ANNUAL_PRODUCT_ID=$VITE_POLAR_STARTUP_ANNUAL_PRODUCT_ID
ARG VITE_POLAR_GROWTH_PRODUCT_ID
ENV VITE_POLAR_GROWTH_PRODUCT_ID=$VITE_POLAR_GROWTH_PRODUCT_ID
ARG VITE_POLAR_GROWTH_ANNUAL_PRODUCT_ID
ENV VITE_POLAR_GROWTH_ANNUAL_PRODUCT_ID=$VITE_POLAR_GROWTH_ANNUAL_PRODUCT_ID

ARG VITE_EMAILJS_SERVICE_ID
ENV VITE_EMAILJS_SERVICE_ID=$VITE_EMAILJS_SERVICE_ID
ARG VITE_EMAILJS_TEMPLATE_ID
ENV VITE_EMAILJS_TEMPLATE_ID=$VITE_EMAILJS_TEMPLATE_ID
ARG VITE_EMAILJS_TEMPLATE_ID_CONTACT
ENV VITE_EMAILJS_TEMPLATE_ID_CONTACT=$VITE_EMAILJS_TEMPLATE_ID_CONTACT
ARG VITE_EMAILJS_PUBLIC_KEY
ENV VITE_EMAILJS_PUBLIC_KEY=$VITE_EMAILJS_PUBLIC_KEY

# Copy package files
COPY package*.json ./

# Install dependencies with retry settings for flaky registry pulls
RUN npm ci --fetch-retries=5 --fetch-retry-mintimeout=20000 --fetch-retry-maxtimeout=120000

# Copy source code
COPY . .

# Build application
RUN npm run build

# Production Stage
FROM nginx:alpine

# Copy built assets from build stage
COPY --from=build /app/dist /usr/share/nginx/html

# Copy nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
