version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/llm-firewall"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "1cbyc"
    assignees:
      - "1cbyc"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "1cbyc"
    assignees:
      - "1cbyc"
    commit-message:
      prefix: "deps"
      include: "scope"