name = "koreshield-web"
pages_build_output_dir = "dist"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[env.production]
routes = [
  { pattern = "koreshield.ai", zone_name = "koreshield.ai" },
  { pattern = "www.koreshield.ai", zone_name = "koreshield.ai" }
]
