import { motion } from 'framer-motion';
import { ArrowLeft } from 'lucide-react';
import { Link, useLocation } from 'react-router-dom';
import { SEOMeta } from '../components/SEOMeta';

const pages: Record<string, { title: string; effective: string; sections: { heading: string; body: string }[] }> = {
	'/privacy-policy': {
		title: 'Privacy Policy',
		effective: '17 April 2026',
		sections: [
			{
				heading: 'Who we are',
				body: 'Koreshield Labs Ltd ("KoreShield", "we", "us", "our") is a company incorporated in England and Wales (Company Number: 17057784), with a registered office at 3rd Floor, 86-90 Paul Street, London, EC2A 4NE. We provide AI security infrastructure — a runtime proxy and detection engine that protects AI applications from prompt injection, RAG poisoning, jailbreaks, PII leakage, and related LLM security threats. Developers and businesses ("Customers" or "Developers") integrate our API and SDK into their AI applications.\n\nFor the purposes of UK GDPR and the Data Protection Act 2018, we act as a data processor when we process personal data on behalf of our Customers as part of the security scanning service, and as a data controller when we process personal data for our own purposes including account management, billing, security operations, and product analytics. This Privacy Policy covers our data controller activities. Our processing of Customer Data as a data processor is governed by our Data Processing Agreement (DPA), available at koreshield.com/legal/dpa.',
			},
			{
				heading: 'The most important thing: zero-log architecture',
				body: 'KoreShield does not log or store raw prompt content. Prompts, system messages, and conversation history submitted to the API are processed in working memory for the duration of the security scan — target: under 50 milliseconds — and are not written to any persistent storage in the default configuration. The threat classification metadata stored in the monitoring dashboard does not include the raw text of the prompt that was scanned. This is not a policy choice we might change in a future update. It is the core architecture of the product.\n\nThe exception is where you (as a Developer) have opted in to audit logging of flagged prompts within your own environment, particularly in the on-premise deployment model. In that case, you control and are responsible for that data.',
			},
			{
				heading: 'Personal data we collect — what you provide',
				body: 'When you register for an account, use the Platform, or contact us, we collect: your name, email address, and company name provided at registration; your password, stored as a bcrypt hash and never in plaintext; billing data processed and stored by Polar, our PCI-compliant payment processor (we do not store full card numbers); the content of support requests, emails, and other communications with us; and any additional profile data you choose to provide.',
			},
			{
				heading: 'Personal data we collect — generated by your use',
				body: 'When you use the KoreShield API and Platform, we collect: API keys, stored as SHA-256 hashes (we do not retain the plaintext after creation); threat classification metadata including threat type, attack category, block decision, severity score, timestamp, and a per-request UUID associated with your customer account identifier (not with individual end users); usage and analytics data including API request volume, scan counts, dashboard activity, and product usage metrics; and security and audit logs including authentication events, administrative access logs, and system security telemetry including IP address at country level.',
			},
			{
				heading: 'How and why we use your data',
				body: 'Account creation and management: to create and maintain your account, authenticate you, and manage API keys (legal basis: performance of contract). Providing and operating the Services: to run the security scanning service and monitoring dashboard (contract). Billing and payment processing: to process subscription payments and issue invoices (contract). Customer support: to respond to support requests and product communications (contract / legitimate interests). Security operations: to detect and respond to security incidents and monitor platform integrity (legitimate interests — protecting our systems and your data). Product analytics: to understand how the Platform is used and improve it (legitimate interests — expected by developers integrating a security product). Threat intelligence improvement: to improve detection models using anonymised aggregated threat pattern data, only where you have opted in (consent). Legal compliance: to meet our obligations under Companies Act, HMRC, and data protection law (legal obligation). Marketing: to send product updates to opted-in subscribers (consent).\n\nWhere we rely on legitimate interests we have assessed that our interests do not override your rights and freedoms. You have the right to object to processing based on legitimate interests — see Your Rights below.',
			},
			{
				heading: 'Prompt content and your end users',
				body: 'When the KoreShield proxy processes prompts from your AI application, those prompts may contain personal data entered by your end users. In this context KoreShield acts as a data processor, processing personal data on your behalf. You are responsible for ensuring you have a lawful basis for sharing your end users\' personal data with KoreShield, obtaining any necessary consents, and disclosing KoreShield\'s role as a sub-processor in your own privacy policy.\n\nEven in our processor role, our zero-log architecture means raw prompt content is not retained after the scan completes. End users\' personal data contained in prompts is processed in memory only and is not stored by KoreShield.',
			},
			{
				heading: 'Threat intelligence and the data flywheel',
				body: 'Our detection engine improves over time through three sources: internal red team datasets and adversarial test cases generated by the KoreShield team; publicly available research, academic literature, and security community datasets on LLM attack techniques including OWASP publications; and optionally, aggregated and anonymised threat pattern data from customer scan activity.\n\nThe default position for all Service Tiers is that your Customer Data does not contribute to our detection models without your explicit opt-in. We will not use your scan data for model improvement unless you have actively consented. If you opt in: only anonymised and aggregated threat pattern data is used — attack technique categories, injection pattern signatures, and detection confidence distributions; raw prompt content is never used for model training; your data is never shared with other customers; and you can withdraw consent at any time via Platform settings without affecting prior processing.\n\nEnterprise Customers can contractually exclude their data from any aggregation as a standard term of the Enterprise Agreement.',
			},
			{
				heading: 'Who we share your data with — sub-processors',
				body: 'We use the following sub-processors. Our full versioned Sub-Processor List is published at koreshield.com/legal/sub-processors.\n\nHetzner Online GmbH (Germany, EU): cloud infrastructure hosting, ISO 27001 certified, our primary data centre. Cloudflare: CDN, DDoS protection, and TLS termination, Privacy Shield certified, SOC 2 Type II. Polar: subscription billing and payment processing, PCI-DSS compliant. Sanity: blog and documentation CMS. EmailJS: transactional email delivery. OpenAI, Google (Gemini / Vertex AI), Microsoft Azure OpenAI: LLM providers used in the detection engine, each governed by their own published DPA and SCCs. DeepSeek: LLM provider used in the detection engine; DeepSeek is incorporated in China and a Transfer Impact Assessment is currently in progress — Enterprise customers with strict data residency requirements should contact privacy@koreshield.com.\n\nWhen our detection engine calls an LLM for semantic analysis, it transmits a structured analysis prompt — not your raw user input verbatim. We do not sell your personal data to third parties and do not operate an advertising model.',
			},
			{
				heading: 'International data transfers',
				body: 'KoreShield\'s primary infrastructure is hosted by Hetzner in Germany (EU). Account data, threat metadata, and operational data are stored within the EEA and do not require further transfer safeguards under UK GDPR. Transfers to LLM sub-processors (OpenAI, Google, Microsoft Azure) outside the UK and EEA are made under International Data Transfer Agreements (IDTAs) or Standard Contractual Clauses (SCCs). Our Cross-Border Data Transfer Policy is available at koreshield.com/legal/transfer-policy.',
			},
			{
				heading: 'Data retention',
				body: 'Raw prompt content: not retained — processed in memory and discarded after each scan. Threat classification metadata: 90 days by default, customer-configurable, deleted within 30 days of account closure. Account data (name, email, company): duration of account plus 12 months post-closure. API keys: until revoked or account closure (SHA-256 hash only — plaintext never retained). Billing records: 7 years from transaction date (Companies Act / HMRC legal obligation). Support communications: 3 years from last interaction. Security and authentication logs: 12 months. Marketing consent records: until withdrawal plus 12 months. Anonymised flywheel data (opt-in only): indefinite, as anonymised data is not subject to retention limits.\n\nOn account closure we will delete or anonymise your personal data within 30 days, except where retention is required by law.',
			},
			{
				heading: 'Your rights under UK GDPR',
				body: 'You have the following rights in relation to personal data we hold about you as data controller. To exercise any of these rights, email privacy@koreshield.com. We will respond within one calendar month.\n\nRight of access (Art. 15): request a copy of the personal data we hold about you. Right to rectification (Art. 16): ask us to correct inaccurate or incomplete data. Right to erasure (Art. 17): ask us to delete your data in certain circumstances. Right to restrict processing (Art. 18): ask us to pause processing while a complaint is investigated. Right to data portability (Art. 20): request your data in a structured machine-readable format where processing is automated and based on consent or contract. Right to object (Art. 21): object to processing based on legitimate interests — we will stop unless we have compelling legitimate grounds. Right to withdraw consent (Art. 7(3)): where we rely on consent, you can withdraw it at any time without affecting prior processing.\n\nNote on prompt data: given our zero-log architecture, DSARs relating to prompt content will receive a response confirming that data is not held. Controller-role data (account information, billing records, support communications) will be provided in response to a valid DSAR.\n\nIf you are not satisfied with how we have handled a privacy concern you can complain to the Information Commissioner\'s Office (ICO) at ico.org.uk or 0303 123 1113.',
			},
			{
				heading: 'Security',
				body: 'We implement appropriate technical and organisational measures to protect your personal data, including: TLS 1.2/1.3 encryption for all data in transit; bcrypt hashing for account passwords; SHA-256 hashing for API keys with plaintext never stored after creation; logical tenant isolation enforced at the API layer and at the PostgreSQL database layer via Row-Level Security; multi-factor authentication required for all administrative access to production systems; and infrastructure hosted in Hetzner\'s ISO 27001 certified EU data centres.\n\nIn the event of a personal data breach that poses a risk to your rights and freedoms we will notify the ICO within 72 hours and notify affected individuals without undue delay where required by UK GDPR Article 34.',
			},
			{
				heading: 'Cookies',
				body: 'We use strictly necessary cookies for authentication and platform security (no consent required) and optional analytics cookies to understand how the Platform is used (consent required). See our Cookie Policy at koreshield.com/cookies for full details including a complete list of every cookie we set, its purpose, duration, and how to manage your preferences.',
			},
			{
				heading: 'Changes to this policy',
				body: 'We may update this Privacy Policy from time to time. For material changes we will notify you by email and/or a prominent notice on the Platform at least 30 days before the change takes effect. The version number and date at the top of this document always reflect the most recent update. Your continued use of the Services after the effective date constitutes acceptance of the changes, except where we are required by law to obtain your explicit consent.',
			},
			{
				heading: 'Contact',
				body: 'Privacy enquiries and Data Subject Access Requests: privacy@koreshield.com (subject line: DSAR Request). Security and breach notifications: security@koreshield.com. Post: Koreshield Labs Ltd, 3rd Floor, 86-90 Paul Street, London, EC2A 4NE. ICO: ico.org.uk · 0303 123 1113.',
			},
		],
	},

	'/terms-of-service': {
		title: 'Terms of Service',
		effective: '17 April 2026',
		sections: [
			{
				heading: 'Important — please read carefully',
				body: 'These Terms of Service ("Terms") constitute a legally binding agreement between you ("Developer" or "Customer") and Koreshield Labs Ltd governing your access to and use of the KoreShield API, SDK, and related services. By accessing or using the Services, you agree to be bound by these Terms. If you are entering into these Terms on behalf of a company or other legal entity, you represent that you have the authority to bind that entity. If you do not have such authority, or if you do not agree to these Terms, you must not access or use the Services.\n\nKoreShield means Koreshield Labs Ltd, a company incorporated in England and Wales with company number 17057784, whose registered office is at 3rd Floor, 86-90 Paul Street, London, EC2A 4NE.',
			},
			{
				heading: 'The Services',
				body: 'KoreShield provides an AI security inspection layer that operates as a reverse proxy between your application and your chosen LLM provider (OpenAI, Anthropic, Google, Azure, or any OpenAI-compatible endpoint). You change the base URL of your LLM API calls to the KoreShield proxy endpoint — no other code change is required. Every API request including the prompt, system message, and conversation history passes through the KoreShield inspection layer before forwarding to the LLM provider. The Services inspect requests and responses in real time, apply your configured detection policies, and either pass the request through or return a structured policy violation response.\n\nCurrent detection coverage includes: direct prompt injection; indirect and RAG-poisoning attacks; PII and credential leakage in both requests and responses; agent tool-call policy enforcement in agentic pipelines; response filtering for data exfiltration attempts; and custom policy rule enforcement. Known coverage gaps are documented in the OWASP LLM Top 10 mapping in the Documentation at docs.koreshield.com.\n\nBy design the Services fail closed: if KoreShield is unavailable, requests do not reach the LLM provider. No unscanned prompt passes through on service failure. Implement appropriate retry logic and fallback handling at your application layer.',
			},
			{
				heading: 'Service tiers',
				body: 'Dev/Free: up to 10,000 protected requests per month, community support via GitHub, no contractual SLA — suitable for development and testing only, not for production applications serving end users at scale.\n\nGrowth: up to 100,000 requests per month, email support with 24-hour response target for standard issues and 4-hour response for Severity 1 incidents, 99.9% uptime SLA.\n\nScale: up to 1,000,000 requests per month, priority support with 4-hour standard and 1-hour Severity 1 response targets, 99.95% uptime SLA.\n\nEnterprise: unlimited requests, custom SLA (target 99.99%), named support contact, on-premise deployment option, custom compliance evidence packages available.\n\nOn reaching your monthly request limit, your account is throttled (soft limit) rather than hard-blocked. KoreShield will notify you via the dashboard and email when approaching the limit. Enterprise customers may negotiate burst allowances.',
			},
			{
				heading: 'Account and API key security',
				body: 'You are responsible for maintaining the confidentiality of your account credentials and API keys, all activities that occur under your account whether or not authorised, and promptly notifying us at security@koreshield.com of any unauthorised access. API keys must be stored securely and must not be embedded in client-side code, committed to public repositories, or shared with unauthorised parties. We display API keys in plaintext only once at creation — you are solely responsible for storing them securely at that point. Separate live and test key types (ks_live_ and ks_test_) are provided to keep test traffic out of production logs.',
			},
			{
				heading: 'Acceptable use — what you may not do',
				body: 'You must not, and must not permit any third party to: use the Services to build offensive attack tools, adversarial prompt injection generation tooling, or any capability designed to attack AI systems or other systems without authorisation; train, fine-tune, or develop a competing LLM security model using our detection outputs, threat classifications, or any data derived from the Services; resell, sub-licence, or white-label the Services without a separate written OEM agreement with KoreShield; reverse-engineer, decompile, or attempt to derive the source code, detection logic, model weights, or proprietary rules of the Services; interfere with or attempt to gain unauthorised access to the Services or connected systems; use the Services to process illegal content or content designed to harm individuals, including CSAM or CBRN-enabling content; use the Services in violation of applicable export control laws or sanctions administered by OFSI, OFAC, or the European Commission; or circumvent rate limits, authentication mechanisms, or the fail-closed proxy architecture.',
			},
			{
				heading: 'Your responsibilities as a developer',
				body: 'You are responsible for: ensuring your use of the Services complies with all applicable laws and regulations; disclosing in your own privacy policy and terms of service that prompts submitted to your application may be processed by KoreShield as a security sub-processor; obtaining all necessary consents from your end users for the processing of their data by the Services; including KoreShield in your sub-processor list if you operate under a DPA with your own customers; and ensuring the security of your integration including the secure storage of API keys. You are also solely responsible for ensuring your use of the Services complies with the terms of service of your chosen LLM provider.',
			},
			{
				heading: 'Intellectual property',
				body: 'All intellectual property rights in the Services, Platform, SDK, Documentation, detection engine, detection models, and threat classification logic are and remain the exclusive property of Koreshield Labs Ltd. Subject to these Terms and payment of applicable fees, we grant you a limited, non-exclusive, non-transferable, revocable licence to access and use the API and Platform for the permitted purpose of protecting your AI applications; integrate and use the SDK in your applications; and use the Documentation in connection with your authorised use of the Services. You retain all intellectual property rights in your own applications and Customer Data. You may not remove or alter any proprietary notices on the Services or SDK, use KoreShield\'s name or trade marks without prior written consent, or represent that your application is developed or endorsed by KoreShield.',
			},
			{
				heading: 'Data processing and privacy',
				body: 'To the extent the Services involve KoreShield processing personal data on your behalf, the parties are bound by the KoreShield Data Processing Agreement (DPA), available at koreshield.com/legal/dpa and incorporated into these Terms by reference. In the event of any conflict between these Terms and the DPA regarding the processing of personal data, the DPA prevails.\n\nKoreShield operates a zero-log default architecture: raw prompt content is not stored. Threat classification metadata is retained for 90 days by default. The default for all tiers is that your data does not contribute to model improvement without your explicit opt-in. Enterprise customers may contractually exclude their data from any aggregation. Our Privacy Policy is at koreshield.com/privacy.',
			},
			{
				heading: 'Billing and payment',
				body: 'Fees for paid tiers are as set out at koreshield.com/pricing or in an Order Form, and are stated exclusive of VAT which will be applied where applicable. Fees are due in advance of the billing period and are processed by Polar, our PCI-DSS compliant payment processor. You may upgrade your tier at any time with immediate effect; downgrades take effect at the end of the current billing period. We may update our pricing with 30 days\' notice; continued use of the Services after a price change constitutes acceptance.',
			},
			{
				heading: 'Service levels and credits',
				body: 'Monthly uptime commitments: Dev/Free — no SLA; Growth — 99.9% (approx. 43.8 minutes downtime per month); Scale — 99.95% (approx. 21.9 minutes per month); Enterprise — custom per contract, target 99.99%.\n\nSLA exclusions include: scheduled maintenance (72 hours advance notice), your system or software failures, LLM provider outages, force majeure, your breach of these Terms, and denial-of-service attacks beyond our reasonable control.\n\nWhere we fail to meet the uptime SLA in a calendar month, your sole remedy is service credits: Growth — 10% credit per hour of Severity 1 outage exceeding the SLA window, capped at 30% of the monthly fee; Scale — 15% per hour capped at 50%; Enterprise — per contract. Credits must be claimed within 30 days of the affected month, are applied to future invoices, and have no cash value.',
			},
			{
				heading: 'Warranties and security disclaimer',
				body: 'We warrant that we have the right to grant the licences in these Terms, the Services will perform materially in accordance with the Documentation, and we will provide the Services with reasonable skill and care. Except as expressly stated, the Services are provided "as is" and "as available".\n\nNo security product provides complete protection against all threats. The Services may not detect all prompt injection, RAG poisoning, jailbreak, or other LLM attack techniques, particularly novel attacks. KoreShield makes no warranty that the Services will prevent all security incidents in your AI application. We are not liable for harm caused by attacks that bypass detection (false negatives). Known detection coverage limitations are documented in the OWASP LLM Top 10 mapping in our Documentation.',
			},
			{
				heading: 'Limitation of liability',
				body: 'To the maximum extent permitted by applicable law, KoreShield\'s total aggregate liability for any claim arising from or in connection with these Terms shall not exceed the greater of: (a) total fees paid by you in the 12 months immediately preceding the event giving rise to the claim; or (b) £1,000.\n\nKoreShield shall not be liable for loss of profits, revenue, business, data, anticipated savings, or goodwill; or for any indirect, special, incidental, punitive, or consequential loss or damage.\n\nNothing in these Terms limits or excludes KoreShield\'s liability for death or personal injury caused by negligence, fraud or fraudulent misrepresentation, or any other liability that cannot be limited by applicable law.',
			},
			{
				heading: 'Confidentiality',
				body: 'Each party agrees to hold the other\'s confidential information in strict confidence, not to use it for any purpose other than performing obligations under these Terms, and to restrict disclosure to those who need to know and are bound by equivalent confidentiality obligations. Confidential information does not include information that is or becomes publicly known through no act of the receiving party, was rightfully in the receiving party\'s possession before disclosure, or is required to be disclosed by law with notice where legally permitted.\n\nKoreShield\'s detection engine logic, model weights, and proprietary rules are and remain KoreShield\'s confidential information. Your application architecture and Customer Data are your confidential information.',
			},
			{
				heading: 'Term and termination',
				body: 'These Terms commence when you first access the Services and continue until terminated. You may cancel at any time by cancelling your subscription in the Platform or emailing legal@koreshield.com; cancellation takes effect at the end of the current billing period.\n\nWe may suspend or terminate your access: immediately if you materially breach the acceptable use or confidentiality provisions; with 30 days\' notice for any other material breach uncured after 14 days\' notice; immediately on your insolvency; or with 30 days\' notice for convenience.\n\nOn termination all licences cease immediately, you must stop using the Services, API, and SDK, and you have 30 days to export your detection log data before account deletion. Accrued payment obligations survive termination, as do the clauses on intellectual property, confidentiality, warranties, limitation of liability, and governing law.',
			},
			{
				heading: 'General',
				body: 'These Terms, together with the DPA, Privacy Policy, Acceptable Use Policy, and any Order Form, constitute the entire agreement between the parties. If any provision is held invalid it will be modified to the minimum extent necessary to make it enforceable; the remainder continues in full force. No failure or delay in exercising any right constitutes a waiver. You may not assign or transfer rights under these Terms without our prior written consent. We may assign these Terms in connection with a merger, acquisition, or sale of assets. Neither party is liable for failure caused by circumstances beyond its reasonable control including LLM provider outages. A person who is not a party to these Terms has no rights under the Contracts (Rights of Third Parties) Act 1999 to enforce any term.',
			},
			{
				heading: 'Governing law',
				body: 'These Terms are governed by the laws of England and Wales. The parties irrevocably submit to the exclusive jurisdiction of the courts of England and Wales, provided that KoreShield may seek injunctive or other equitable relief in any court of competent jurisdiction to protect its intellectual property rights or confidential information.',
			},
			{
				heading: 'Contact',
				body: 'Legal enquiries: legal@koreshield.com. Security and vulnerability disclosure: security@koreshield.com. Support: support@koreshield.com. Post: Koreshield Labs Ltd, 3rd Floor, 86-90 Paul Street, London, EC2A 4NE.',
			},
		],
	},

	'/cookie-policy': {
		title: 'Cookie Policy',
		effective: '17 April 2026',
		sections: [
			{
				heading: 'What are cookies?',
				body: 'Cookies are small text files placed on your device when you visit a website or use a web application. We also use local storage and session storage in your browser where necessary for the Platform to function — references to "cookies" in this policy include these similar technologies. KoreShield uses cookies for two purposes only: making the Platform work securely, and understanding how the Platform is used so we can improve it.',
			},
			{
				heading: 'What we do not do',
				body: 'We do not use cookies for advertising, retargeting, or behavioural profiling. We do not set or permit advertising or retargeting cookies of any kind, third-party social media tracking pixels (Facebook, LinkedIn, Twitter/X, or others), cross-site tracking cookies that follow you beyond our own domains, or fingerprinting scripts. We do not sell or share cookie data with advertising networks or data brokers. KoreShield products are ad-free.',
			},
			{
				heading: 'Strictly necessary cookies',
				body: 'These cookies are required for the Platform to function and cannot be disabled. No consent is required for these cookies under the UK Privacy and Electronic Communications Regulations (PECR).\n\nks_session: authenticates your logged-in session. Set as HttpOnly, Secure, and SameSite=Strict. Signed as a JWT using HS256. Expires on browser close or after 24 hours of inactivity.\n\nks_csrf: CSRF protection token for form submissions and state-changing API requests. Session duration.\n\nks_oauth_state: per-request state token for OAuth login flows (GitHub and Google). Protects against CSRF during authentication. Stored in Redis server-side with a 10-minute TTL; the cookie expires correspondingly.\n\nks_prefs: stores your in-session UI preferences such as dashboard layout and selected filters. Contains no personal data. Session duration.\n\ncookie_consent: records your cookie consent choice so we do not present the consent banner on return visits. Retained for 12 months.',
			},
			{
				heading: 'Analytics cookies',
				body: 'These cookies are set only with your consent. They help us understand how developers use the Platform and documentation so we can improve the product. We do not use Google Analytics, Hotjar, Intercom, Segment, HubSpot, or any other third-party analytics platform that would track you across other websites.\n\nks_analytics: tracks anonymised usage events within the Platform — pages visited, features used, API call counts. No prompt content, no personal identifiers, no cross-site tracking. Retained for 30 days.\n\nks_docs_session: tracks anonymised documentation page views to understand which guides are most used. No personal identifiers. Session duration.',
			},
			{
				heading: 'Third-party cookies — Cloudflare',
				body: 'Our Platform uses Cloudflare for CDN and DDoS protection. Cloudflare may set the following cookies as a necessary part of the infrastructure that keeps the Platform available and secure — these are set by Cloudflare, not by KoreShield.\n\n__cf_bm: bot management cookie that distinguishes between human visitors and automated traffic. Duration: 30 minutes.\n\n_cfuvid: used by Cloudflare for rate limiting. Not set for all visitors. Session duration.\n\nThese are the only third-party cookies on our Platform. See Cloudflare\'s Cookie Policy at cloudflare.com/cookie-policy for more detail.',
			},
			{
				heading: 'Managing your preferences',
				body: 'When you first visit the Platform or website you will be presented with a cookie consent banner where you can accept all cookies, accept necessary cookies only, or manage your preferences by category. You can update your choices at any time by clicking the Cookie Settings link in the footer of any page on koreshield.com or app.koreshield.com.\n\nYou can also control cookies through your browser settings — you can view, delete, or block cookies, and set your browser to notify you before a cookie is set. Note that disabling strictly necessary cookies will prevent you from logging in to the Platform.',
			},
			{
				heading: 'Withdrawing consent',
				body: 'You can withdraw consent for analytics cookies at any time via the cookie settings control on the Platform. Withdrawal does not affect the lawfulness of processing that occurred before withdrawal. When you withdraw consent, analytics cookies will be deleted from your device and will not be reset until you consent again.',
			},
			{
				heading: 'Do Not Track',
				body: 'Some browsers send a Do Not Track (DNT) signal to websites. We respect DNT signals: if your browser sends a DNT signal we will not set analytics cookies for your session, regardless of your saved cookie preferences.',
			},
			{
				heading: 'Changes to this policy',
				body: 'We may update this Cookie Policy from time to time to reflect changes in the cookies we use or in applicable law. We will notify you of material changes by updating the version number and date at the top of this document and, where required, by presenting a new consent banner on your next visit. Your continued use of the Platform after the effective date constitutes your acceptance of the changes.',
			},
			{
				heading: 'Contact',
				body: 'Questions about this Cookie Policy or how we use cookies: privacy@koreshield.com. Data controller: Koreshield Labs Ltd, 3rd Floor, 86-90 Paul Street, London, EC2A 4NE (Co. No. 17057784). Supervisory authority: Information Commissioner\'s Office, ico.org.uk, 0303 123 1113.\n\nThis Cookie Policy should be read alongside our Privacy Policy (koreshield.com/privacy) and Terms of Service (koreshield.com/terms).',
			},
		],
	},
};

export default function LegalPage() {
	const { pathname } = useLocation();
	const page = pages[pathname];

	if (!page) return null;

	return (
		<div className="min-h-screen bg-background text-foreground transition-colors">
			<SEOMeta title={page.title} description={`KoreShield ${page.title}`} />

			<div className="max-w-3xl mx-auto px-6 py-20">
				<motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
					<Link to="/" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors mb-10">
						<ArrowLeft className="w-4 h-4" />
						Back to home
					</Link>

					<h1 className="text-4xl font-extrabold text-foreground mb-2 tracking-tight">{page.title}</h1>
					<p className="text-sm text-muted-foreground mb-12">Effective {page.effective} · Koreshield Labs Ltd</p>

					<div className="space-y-10">
						{page.sections.map((s) => (
							<div key={s.heading}>
								<h2 className="text-lg font-semibold text-foreground mb-3">{s.heading}</h2>
								<p className="text-muted-foreground leading-relaxed text-sm">{s.body}</p>
							</div>
						))}
					</div>

					<div className="mt-16 pt-8 border-t border-border text-xs text-muted-foreground">
						Questions? Email{' '}
						<a href="mailto:hello@koreshield.com" className="text-primary hover:underline">hello@koreshield.com</a>
					</div>
				</motion.div>
			</div>
		</div>
	);
}
