"""KoreShield Python SDK - LLM Security Platform SDK

A comprehensive Python SDK for integrating KoreShield's LLM security features
into your applications with ease.
"""

from .client import KoreShieldClient
from .async_client import AsyncKoreShieldClient
from .exceptions import (
    KoreShieldError,
    AuthenticationError,
    ValidationError,
    RateLimitError,
    ServerError,
    NetworkError,
    TimeoutError,
)
from .local_security import (
    normalize_text,
    preflight_scan_prompt,
    preflight_scan_rag_context,
    preflight_scan_tool_call,
)
from .types import (
    DetectionResult,
    ScanRequest,
    ScanResponse,
    ThreatLevel,
    DetectionType,
    AuthConfig,
    SecurityPolicy,
    PerformanceMetrics,
    StreamingScanResponse,
    DetectionIndicator,
    BatchScanRequest,
    BatchScanResponse,
    LocalPreflightResult,
    NormalizationResult,
    ToolCapability,
    RAGPreflightDocumentResult,
    RAGPreflightResult,
    RAGStatistics,
    ToolScanPolicyResult,
    ToolScanPolicyViolation,
    ToolScanResponse,
    ToolCallPreflightResult,
    ToolRiskClass,
    ToolTrustContext,
    DocumentThreatMetadata,
    CrossDocumentThreatMetadata,
    QueryAnalysis,
)
from .types import (
    RAGDocument,
    RAGScanRequest,
    RAGScanResponse,
    DocumentThreat,
    CrossDocumentThreat,
)

__version__ = "0.3.5"
__all__ = [
    "KoreShieldClient",
    "AsyncKoreShieldClient",
    "KoreShieldError",
    "AuthenticationError",
    "ValidationError",
    "RateLimitError",
    "ServerError",
    "NetworkError",
    "TimeoutError",
    "normalize_text",
    "preflight_scan_prompt",
    "preflight_scan_rag_context",
    "preflight_scan_tool_call",
    "DetectionResult",
    "ScanRequest",
    "ScanResponse",
    "ThreatLevel",
    "DetectionType",
    "AuthConfig",
    "SecurityPolicy",
    "PerformanceMetrics",
    "StreamingScanResponse",
    "DetectionIndicator",
    "BatchScanRequest",
    "BatchScanResponse",
    "LocalPreflightResult",
    "NormalizationResult",
    "ToolCapability",
    "RAGPreflightDocumentResult",
    "RAGPreflightResult",
    "RAGStatistics",
    "ToolScanPolicyResult",
    "ToolScanPolicyViolation",
    "ToolScanResponse",
    "ToolCallPreflightResult",
    "ToolRiskClass",
    "ToolTrustContext",
    "DocumentThreatMetadata",
    "CrossDocumentThreatMetadata",
    "QueryAnalysis",
    "RAGDocument",
    "RAGScanRequest",
    "RAGScanResponse",
    "DocumentThreat",
    "CrossDocumentThreat",
]
