/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectRouteImport } from './routes/select'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmailTemplatesRouteImport } from './routes/email-templates'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as OrgSlugRouteImport } from './routes/$orgSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug/index'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations.accept'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as CliLoginRouteImport } from './routes/cli.login'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminChartsRouteImport } from './routes/admin/charts'
import { Route as OrgSlugTokensRouteImport } from './routes/$orgSlug/tokens'
import { Route as OrgSlugSettingsRouteImport } from './routes/$orgSlug/settings'
import { Route as OrgSlugRequestsRouteImport } from './routes/$orgSlug/requests'
import { Route as OrgSlugMembersRouteImport } from './routes/$orgSlug/members'
import { Route as OrgSlugInstallRouteImport } from './routes/$orgSlug/install'
import { Route as OrgSlugFirewallRouteImport } from './routes/$orgSlug/firewall'
import { Route as OrgSlugBillingRouteImport } from './routes/$orgSlug/billing'
import { Route as AdminOrganizationsIndexRouteImport } from './routes/admin/organizations.index'
import { Route as OrgSlugSettingsIndexRouteImport } from './routes/$orgSlug/settings/index'
import { Route as ApiWebhooksPolarRouteImport } from './routes/api/webhooks/polar'
import { Route as ApiSubscriptionsOrganizationIdRouteImport } from './routes/api/subscriptions/$organizationId'
import { Route as ApiOrganizationsCheckSlugRouteImport } from './routes/api/organizations/check-slug'
import { Route as ApiMeOrgsRouteImport } from './routes/api/me/orgs'
import { Route as ApiDashboardWsTokenRouteImport } from './routes/api/dashboard/ws-token'
import { Route as ApiDashboardValidateWsTokenRouteImport } from './routes/api/dashboard/validate-ws-token'
import { Route as ApiCliLoginRouteImport } from './routes/api/cli/login'
import { Route as ApiCliExchangeRouteImport } from './routes/api/cli/exchange'
import { Route as ApiCliCompleteRouteImport } from './routes/api/cli/complete'
import { Route as ApiCheckoutPolarRouteImport } from './routes/api/checkout/polar'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminSubscriptionsRouteImport } from './routes/api/admin/subscriptions'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminOverviewRouteImport } from './routes/api/admin/overview'
import { Route as ApiAdminOrganizationsRouteImport } from './routes/api/admin/organizations'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminChartsRouteImport } from './routes/api/admin/charts'
import { Route as ApiOrgSlugSubscriptionsRouteImport } from './routes/api/$orgSlug/subscriptions'
import { Route as ApiOrgSlugSettingsRouteImport } from './routes/api/$orgSlug/settings'
import { Route as ApiOrgSlugRequestsRouteImport } from './routes/api/$orgSlug/requests'
import { Route as ApiOrgSlugAuthTokensRouteImport } from './routes/api/$orgSlug/auth-tokens'
import { Route as AdminOrganizationsSlugRouteImport } from './routes/admin/organizations.$slug'
import { Route as OrgSlugSettingsProfileRouteImport } from './routes/$orgSlug/settings/profile'
import { Route as OrgSlugSettingsOrganizationRouteImport } from './routes/$orgSlug/settings/organization'
import { Route as ApiCliLoginStatusRouteImport } from './routes/api/cli/login/status'
import { Route as ApiAdminOrganizationsSlugRouteImport } from './routes/api/admin/organizations.$slug'
import { Route as ApiOrgSlugRequestsReplayRouteImport } from './routes/api/$orgSlug/requests/replay'
import { Route as ApiOrgSlugRequestsCaptureRouteImport } from './routes/api/$orgSlug/requests/capture'
import { Route as ApiOrgSlugPortalPolarRouteImport } from './routes/api/$orgSlug/portal/polar'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTemplatesRoute = EmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRoute,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CliLoginRoute = CliLoginRouteImport.update({
  id: '/cli/login',
  path: '/cli/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChartsRoute = AdminChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => AdminRoute,
} as any)
const OrgSlugTokensRoute = OrgSlugTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugSettingsRoute = OrgSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugRequestsRoute = OrgSlugRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugMembersRoute = OrgSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugInstallRoute = OrgSlugInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugFirewallRoute = OrgSlugFirewallRouteImport.update({
  id: '/firewall',
  path: '/firewall',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugBillingRoute = OrgSlugBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => OrgSlugRoute,
} as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AdminRoute,
} as any)
const OrgSlugSettingsIndexRoute = OrgSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugSettingsRoute,
} as any)
const ApiWebhooksPolarRoute = ApiWebhooksPolarRouteImport.update({
  id: '/api/webhooks/polar',
  path: '/api/webhooks/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionsOrganizationIdRoute =
  ApiSubscriptionsOrganizationIdRouteImport.update({
    id: '/api/subscriptions/$organizationId',
    path: '/api/subscriptions/$organizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrganizationsCheckSlugRoute =
  ApiOrganizationsCheckSlugRouteImport.update({
    id: '/api/organizations/check-slug',
    path: '/api/organizations/check-slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeOrgsRoute = ApiMeOrgsRouteImport.update({
  id: '/api/me/orgs',
  path: '/api/me/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardWsTokenRoute = ApiDashboardWsTokenRouteImport.update({
  id: '/api/dashboard/ws-token',
  path: '/api/dashboard/ws-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardValidateWsTokenRoute =
  ApiDashboardValidateWsTokenRouteImport.update({
    id: '/api/dashboard/validate-ws-token',
    path: '/api/dashboard/validate-ws-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCliLoginRoute = ApiCliLoginRouteImport.update({
  id: '/api/cli/login',
  path: '/api/cli/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliExchangeRoute = ApiCliExchangeRouteImport.update({
  id: '/api/cli/exchange',
  path: '/api/cli/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliCompleteRoute = ApiCliCompleteRouteImport.update({
  id: '/api/cli/complete',
  path: '/api/cli/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutPolarRoute = ApiCheckoutPolarRouteImport.update({
  id: '/api/checkout/polar',
  path: '/api/checkout/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubscriptionsRoute = ApiAdminSubscriptionsRouteImport.update({
  id: '/api/admin/subscriptions',
  path: '/api/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOverviewRoute = ApiAdminOverviewRouteImport.update({
  id: '/api/admin/overview',
  path: '/api/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrganizationsRoute = ApiAdminOrganizationsRouteImport.update({
  id: '/api/admin/organizations',
  path: '/api/admin/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminChartsRoute = ApiAdminChartsRouteImport.update({
  id: '/api/admin/charts',
  path: '/api/admin/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugSubscriptionsRoute = ApiOrgSlugSubscriptionsRouteImport.update({
  id: '/api/$orgSlug/subscriptions',
  path: '/api/$orgSlug/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugSettingsRoute = ApiOrgSlugSettingsRouteImport.update({
  id: '/api/$orgSlug/settings',
  path: '/api/$orgSlug/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugRequestsRoute = ApiOrgSlugRequestsRouteImport.update({
  id: '/api/$orgSlug/requests',
  path: '/api/$orgSlug/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgSlugAuthTokensRoute = ApiOrgSlugAuthTokensRouteImport.update({
  id: '/api/$orgSlug/auth-tokens',
  path: '/api/$orgSlug/auth-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsSlugRoute = AdminOrganizationsSlugRouteImport.update({
  id: '/organizations/$slug',
  path: '/organizations/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const OrgSlugSettingsProfileRoute = OrgSlugSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OrgSlugSettingsRoute,
} as any)
const OrgSlugSettingsOrganizationRoute =
  OrgSlugSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => OrgSlugSettingsRoute,
  } as any)
const ApiCliLoginStatusRoute = ApiCliLoginStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiCliLoginRoute,
} as any)
const ApiAdminOrganizationsSlugRoute =
  ApiAdminOrganizationsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => ApiAdminOrganizationsRoute,
  } as any)
const ApiOrgSlugRequestsReplayRoute =
  ApiOrgSlugRequestsReplayRouteImport.update({
    id: '/replay',
    path: '/replay',
    getParentRoute: () => ApiOrgSlugRequestsRoute,
  } as any)
const ApiOrgSlugRequestsCaptureRoute =
  ApiOrgSlugRequestsCaptureRouteImport.update({
    id: '/capture',
    path: '/capture',
    getParentRoute: () => ApiOrgSlugRequestsRoute,
  } as any)
const ApiOrgSlugPortalPolarRoute = ApiOrgSlugPortalPolarRouteImport.update({
  id: '/api/$orgSlug/portal/polar',
  path: '/api/$orgSlug/portal/polar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/email-templates': typeof EmailTemplatesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/select': typeof SelectRoute
  '/signup': typeof SignupRoute
  '/$orgSlug/billing': typeof OrgSlugBillingRoute
  '/$orgSlug/firewall': typeof OrgSlugFirewallRoute
  '/$orgSlug/install': typeof OrgSlugInstallRoute
  '/$orgSlug/members': typeof OrgSlugMembersRoute
  '/$orgSlug/requests': typeof OrgSlugRequestsRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteWithChildren
  '/$orgSlug/tokens': typeof OrgSlugTokensRoute
  '/admin/charts': typeof AdminChartsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/search': typeof ApiSearchRoute
  '/cli/login': typeof CliLoginRoute
  '/docs/$': typeof DocsSplatRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/profile': typeof OrgSlugSettingsProfileRoute
  '/admin/organizations/$slug': typeof AdminOrganizationsSlugRoute
  '/api/$orgSlug/auth-tokens': typeof ApiOrgSlugAuthTokensRoute
  '/api/$orgSlug/requests': typeof ApiOrgSlugRequestsRouteWithChildren
  '/api/$orgSlug/settings': typeof ApiOrgSlugSettingsRoute
  '/api/$orgSlug/subscriptions': typeof ApiOrgSlugSubscriptionsRoute
  '/api/admin/charts': typeof ApiAdminChartsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/organizations': typeof ApiAdminOrganizationsRouteWithChildren
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/subscriptions': typeof ApiAdminSubscriptionsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/dashboard/validate-ws-token': typeof ApiDashboardValidateWsTokenRoute
  '/api/dashboard/ws-token': typeof ApiDashboardWsTokenRoute
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/organizations/check-slug': typeof ApiOrganizationsCheckSlugRoute
  '/api/subscriptions/$organizationId': typeof ApiSubscriptionsOrganizationIdRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/api/$orgSlug/portal/polar': typeof ApiOrgSlugPortalPolarRoute
  '/api/$orgSlug/requests/capture': typeof ApiOrgSlugRequestsCaptureRoute
  '/api/$orgSlug/requests/replay': typeof ApiOrgSlugRequestsReplayRoute
  '/api/admin/organizations/$slug': typeof ApiAdminOrganizationsSlugRoute
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/email-templates': typeof EmailTemplatesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/select': typeof SelectRoute
  '/signup': typeof SignupRoute
  '/$orgSlug/billing': typeof OrgSlugBillingRoute
  '/$orgSlug/firewall': typeof OrgSlugFirewallRoute
  '/$orgSlug/install': typeof OrgSlugInstallRoute
  '/$orgSlug/members': typeof OrgSlugMembersRoute
  '/$orgSlug/requests': typeof OrgSlugRequestsRoute
  '/$orgSlug/tokens': typeof OrgSlugTokensRoute
  '/admin/charts': typeof AdminChartsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/search': typeof ApiSearchRoute
  '/cli/login': typeof CliLoginRoute
  '/docs/$': typeof DocsSplatRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/profile': typeof OrgSlugSettingsProfileRoute
  '/admin/organizations/$slug': typeof AdminOrganizationsSlugRoute
  '/api/$orgSlug/auth-tokens': typeof ApiOrgSlugAuthTokensRoute
  '/api/$orgSlug/requests': typeof ApiOrgSlugRequestsRouteWithChildren
  '/api/$orgSlug/settings': typeof ApiOrgSlugSettingsRoute
  '/api/$orgSlug/subscriptions': typeof ApiOrgSlugSubscriptionsRoute
  '/api/admin/charts': typeof ApiAdminChartsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/organizations': typeof ApiAdminOrganizationsRouteWithChildren
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/subscriptions': typeof ApiAdminSubscriptionsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/dashboard/validate-ws-token': typeof ApiDashboardValidateWsTokenRoute
  '/api/dashboard/ws-token': typeof ApiDashboardWsTokenRoute
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/organizations/check-slug': typeof ApiOrganizationsCheckSlugRoute
  '/api/subscriptions/$organizationId': typeof ApiSubscriptionsOrganizationIdRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsIndexRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/api/$orgSlug/portal/polar': typeof ApiOrgSlugPortalPolarRoute
  '/api/$orgSlug/requests/capture': typeof ApiOrgSlugRequestsCaptureRoute
  '/api/$orgSlug/requests/replay': typeof ApiOrgSlugRequestsReplayRoute
  '/api/admin/organizations/$slug': typeof ApiAdminOrganizationsSlugRoute
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/email-templates': typeof EmailTemplatesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/select': typeof SelectRoute
  '/signup': typeof SignupRoute
  '/$orgSlug/billing': typeof OrgSlugBillingRoute
  '/$orgSlug/firewall': typeof OrgSlugFirewallRoute
  '/$orgSlug/install': typeof OrgSlugInstallRoute
  '/$orgSlug/members': typeof OrgSlugMembersRoute
  '/$orgSlug/requests': typeof OrgSlugRequestsRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteWithChildren
  '/$orgSlug/tokens': typeof OrgSlugTokensRoute
  '/admin/charts': typeof AdminChartsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/search': typeof ApiSearchRoute
  '/cli/login': typeof CliLoginRoute
  '/docs/$': typeof DocsSplatRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/profile': typeof OrgSlugSettingsProfileRoute
  '/admin/organizations/$slug': typeof AdminOrganizationsSlugRoute
  '/api/$orgSlug/auth-tokens': typeof ApiOrgSlugAuthTokensRoute
  '/api/$orgSlug/requests': typeof ApiOrgSlugRequestsRouteWithChildren
  '/api/$orgSlug/settings': typeof ApiOrgSlugSettingsRoute
  '/api/$orgSlug/subscriptions': typeof ApiOrgSlugSubscriptionsRoute
  '/api/admin/charts': typeof ApiAdminChartsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/organizations': typeof ApiAdminOrganizationsRouteWithChildren
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/subscriptions': typeof ApiAdminSubscriptionsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/dashboard/validate-ws-token': typeof ApiDashboardValidateWsTokenRoute
  '/api/dashboard/ws-token': typeof ApiDashboardWsTokenRoute
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/organizations/check-slug': typeof ApiOrganizationsCheckSlugRoute
  '/api/subscriptions/$organizationId': typeof ApiSubscriptionsOrganizationIdRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/api/$orgSlug/portal/polar': typeof ApiOrgSlugPortalPolarRoute
  '/api/$orgSlug/requests/capture': typeof ApiOrgSlugRequestsCaptureRoute
  '/api/$orgSlug/requests/replay': typeof ApiOrgSlugRequestsReplayRoute
  '/api/admin/organizations/$slug': typeof ApiAdminOrganizationsSlugRoute
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/admin'
    | '/email-templates'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/select'
    | '/signup'
    | '/$orgSlug/billing'
    | '/$orgSlug/firewall'
    | '/$orgSlug/install'
    | '/$orgSlug/members'
    | '/$orgSlug/requests'
    | '/$orgSlug/settings'
    | '/$orgSlug/tokens'
    | '/admin/charts'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/api/search'
    | '/cli/login'
    | '/docs/$'
    | '/invitations/accept'
    | '/$orgSlug/'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/profile'
    | '/admin/organizations/$slug'
    | '/api/$orgSlug/auth-tokens'
    | '/api/$orgSlug/requests'
    | '/api/$orgSlug/settings'
    | '/api/$orgSlug/subscriptions'
    | '/api/admin/charts'
    | '/api/admin/login'
    | '/api/admin/organizations'
    | '/api/admin/overview'
    | '/api/admin/stats'
    | '/api/admin/subscriptions'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/dashboard/validate-ws-token'
    | '/api/dashboard/ws-token'
    | '/api/me/orgs'
    | '/api/organizations/check-slug'
    | '/api/subscriptions/$organizationId'
    | '/api/webhooks/polar'
    | '/$orgSlug/settings/'
    | '/admin/organizations/'
    | '/api/$orgSlug/portal/polar'
    | '/api/$orgSlug/requests/capture'
    | '/api/$orgSlug/requests/replay'
    | '/api/admin/organizations/$slug'
    | '/api/cli/login/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/email-templates'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/select'
    | '/signup'
    | '/$orgSlug/billing'
    | '/$orgSlug/firewall'
    | '/$orgSlug/install'
    | '/$orgSlug/members'
    | '/$orgSlug/requests'
    | '/$orgSlug/tokens'
    | '/admin/charts'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/api/search'
    | '/cli/login'
    | '/docs/$'
    | '/invitations/accept'
    | '/$orgSlug'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/profile'
    | '/admin/organizations/$slug'
    | '/api/$orgSlug/auth-tokens'
    | '/api/$orgSlug/requests'
    | '/api/$orgSlug/settings'
    | '/api/$orgSlug/subscriptions'
    | '/api/admin/charts'
    | '/api/admin/login'
    | '/api/admin/organizations'
    | '/api/admin/overview'
    | '/api/admin/stats'
    | '/api/admin/subscriptions'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/dashboard/validate-ws-token'
    | '/api/dashboard/ws-token'
    | '/api/me/orgs'
    | '/api/organizations/check-slug'
    | '/api/subscriptions/$organizationId'
    | '/api/webhooks/polar'
    | '/$orgSlug/settings'
    | '/admin/organizations'
    | '/api/$orgSlug/portal/polar'
    | '/api/$orgSlug/requests/capture'
    | '/api/$orgSlug/requests/replay'
    | '/api/admin/organizations/$slug'
    | '/api/cli/login/status'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/admin'
    | '/email-templates'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/select'
    | '/signup'
    | '/$orgSlug/billing'
    | '/$orgSlug/firewall'
    | '/$orgSlug/install'
    | '/$orgSlug/members'
    | '/$orgSlug/requests'
    | '/$orgSlug/settings'
    | '/$orgSlug/tokens'
    | '/admin/charts'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/api/search'
    | '/cli/login'
    | '/docs/$'
    | '/invitations/accept'
    | '/$orgSlug/'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/profile'
    | '/admin/organizations/$slug'
    | '/api/$orgSlug/auth-tokens'
    | '/api/$orgSlug/requests'
    | '/api/$orgSlug/settings'
    | '/api/$orgSlug/subscriptions'
    | '/api/admin/charts'
    | '/api/admin/login'
    | '/api/admin/organizations'
    | '/api/admin/overview'
    | '/api/admin/stats'
    | '/api/admin/subscriptions'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/dashboard/validate-ws-token'
    | '/api/dashboard/ws-token'
    | '/api/me/orgs'
    | '/api/organizations/check-slug'
    | '/api/subscriptions/$organizationId'
    | '/api/webhooks/polar'
    | '/$orgSlug/settings/'
    | '/admin/organizations/'
    | '/api/$orgSlug/portal/polar'
    | '/api/$orgSlug/requests/capture'
    | '/api/$orgSlug/requests/replay'
    | '/api/admin/organizations/$slug'
    | '/api/cli/login/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRoute: typeof OrgSlugRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  EmailTemplatesRoute: typeof EmailTemplatesRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  SelectRoute: typeof SelectRoute
  SignupRoute: typeof SignupRoute
  ApiSearchRoute: typeof ApiSearchRoute
  CliLoginRoute: typeof CliLoginRoute
  DocsSplatRoute: typeof DocsSplatRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
  ApiOrgSlugAuthTokensRoute: typeof ApiOrgSlugAuthTokensRoute
  ApiOrgSlugRequestsRoute: typeof ApiOrgSlugRequestsRouteWithChildren
  ApiOrgSlugSettingsRoute: typeof ApiOrgSlugSettingsRoute
  ApiOrgSlugSubscriptionsRoute: typeof ApiOrgSlugSubscriptionsRoute
  ApiAdminChartsRoute: typeof ApiAdminChartsRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminOrganizationsRoute: typeof ApiAdminOrganizationsRouteWithChildren
  ApiAdminOverviewRoute: typeof ApiAdminOverviewRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminSubscriptionsRoute: typeof ApiAdminSubscriptionsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCheckoutPolarRoute: typeof ApiCheckoutPolarRoute
  ApiCliCompleteRoute: typeof ApiCliCompleteRoute
  ApiCliExchangeRoute: typeof ApiCliExchangeRoute
  ApiCliLoginRoute: typeof ApiCliLoginRouteWithChildren
  ApiDashboardValidateWsTokenRoute: typeof ApiDashboardValidateWsTokenRoute
  ApiDashboardWsTokenRoute: typeof ApiDashboardWsTokenRoute
  ApiMeOrgsRoute: typeof ApiMeOrgsRoute
  ApiOrganizationsCheckSlugRoute: typeof ApiOrganizationsCheckSlugRoute
  ApiSubscriptionsOrganizationIdRoute: typeof ApiSubscriptionsOrganizationIdRoute
  ApiWebhooksPolarRoute: typeof ApiWebhooksPolarRoute
  ApiOrgSlugPortalPolarRoute: typeof ApiOrgSlugPortalPolarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-templates': {
      id: '/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof EmailTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/login': {
      id: '/cli/login'
      path: '/cli/login'
      fullPath: '/cli/login'
      preLoaderRoute: typeof CliLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/charts': {
      id: '/admin/charts'
      path: '/charts'
      fullPath: '/admin/charts'
      preLoaderRoute: typeof AdminChartsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$orgSlug/tokens': {
      id: '/$orgSlug/tokens'
      path: '/tokens'
      fullPath: '/$orgSlug/tokens'
      preLoaderRoute: typeof OrgSlugTokensRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/settings': {
      id: '/$orgSlug/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof OrgSlugSettingsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/requests': {
      id: '/$orgSlug/requests'
      path: '/requests'
      fullPath: '/$orgSlug/requests'
      preLoaderRoute: typeof OrgSlugRequestsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/members': {
      id: '/$orgSlug/members'
      path: '/members'
      fullPath: '/$orgSlug/members'
      preLoaderRoute: typeof OrgSlugMembersRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/install': {
      id: '/$orgSlug/install'
      path: '/install'
      fullPath: '/$orgSlug/install'
      preLoaderRoute: typeof OrgSlugInstallRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/firewall': {
      id: '/$orgSlug/firewall'
      path: '/firewall'
      fullPath: '/$orgSlug/firewall'
      preLoaderRoute: typeof OrgSlugFirewallRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/billing': {
      id: '/$orgSlug/billing'
      path: '/billing'
      fullPath: '/$orgSlug/billing'
      preLoaderRoute: typeof OrgSlugBillingRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/admin/organizations/': {
      id: '/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$orgSlug/settings/': {
      id: '/$orgSlug/settings/'
      path: '/'
      fullPath: '/$orgSlug/settings/'
      preLoaderRoute: typeof OrgSlugSettingsIndexRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/api/webhooks/polar': {
      id: '/api/webhooks/polar'
      path: '/api/webhooks/polar'
      fullPath: '/api/webhooks/polar'
      preLoaderRoute: typeof ApiWebhooksPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscriptions/$organizationId': {
      id: '/api/subscriptions/$organizationId'
      path: '/api/subscriptions/$organizationId'
      fullPath: '/api/subscriptions/$organizationId'
      preLoaderRoute: typeof ApiSubscriptionsOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations/check-slug': {
      id: '/api/organizations/check-slug'
      path: '/api/organizations/check-slug'
      fullPath: '/api/organizations/check-slug'
      preLoaderRoute: typeof ApiOrganizationsCheckSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/orgs': {
      id: '/api/me/orgs'
      path: '/api/me/orgs'
      fullPath: '/api/me/orgs'
      preLoaderRoute: typeof ApiMeOrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/ws-token': {
      id: '/api/dashboard/ws-token'
      path: '/api/dashboard/ws-token'
      fullPath: '/api/dashboard/ws-token'
      preLoaderRoute: typeof ApiDashboardWsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/validate-ws-token': {
      id: '/api/dashboard/validate-ws-token'
      path: '/api/dashboard/validate-ws-token'
      fullPath: '/api/dashboard/validate-ws-token'
      preLoaderRoute: typeof ApiDashboardValidateWsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/login': {
      id: '/api/cli/login'
      path: '/api/cli/login'
      fullPath: '/api/cli/login'
      preLoaderRoute: typeof ApiCliLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/exchange': {
      id: '/api/cli/exchange'
      path: '/api/cli/exchange'
      fullPath: '/api/cli/exchange'
      preLoaderRoute: typeof ApiCliExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/complete': {
      id: '/api/cli/complete'
      path: '/api/cli/complete'
      fullPath: '/api/cli/complete'
      preLoaderRoute: typeof ApiCliCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/polar': {
      id: '/api/checkout/polar'
      path: '/api/checkout/polar'
      fullPath: '/api/checkout/polar'
      preLoaderRoute: typeof ApiCheckoutPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/subscriptions': {
      id: '/api/admin/subscriptions'
      path: '/api/admin/subscriptions'
      fullPath: '/api/admin/subscriptions'
      preLoaderRoute: typeof ApiAdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/overview': {
      id: '/api/admin/overview'
      path: '/api/admin/overview'
      fullPath: '/api/admin/overview'
      preLoaderRoute: typeof ApiAdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/organizations': {
      id: '/api/admin/organizations'
      path: '/api/admin/organizations'
      fullPath: '/api/admin/organizations'
      preLoaderRoute: typeof ApiAdminOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/charts': {
      id: '/api/admin/charts'
      path: '/api/admin/charts'
      fullPath: '/api/admin/charts'
      preLoaderRoute: typeof ApiAdminChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/subscriptions': {
      id: '/api/$orgSlug/subscriptions'
      path: '/api/$orgSlug/subscriptions'
      fullPath: '/api/$orgSlug/subscriptions'
      preLoaderRoute: typeof ApiOrgSlugSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/settings': {
      id: '/api/$orgSlug/settings'
      path: '/api/$orgSlug/settings'
      fullPath: '/api/$orgSlug/settings'
      preLoaderRoute: typeof ApiOrgSlugSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/requests': {
      id: '/api/$orgSlug/requests'
      path: '/api/$orgSlug/requests'
      fullPath: '/api/$orgSlug/requests'
      preLoaderRoute: typeof ApiOrgSlugRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/auth-tokens': {
      id: '/api/$orgSlug/auth-tokens'
      path: '/api/$orgSlug/auth-tokens'
      fullPath: '/api/$orgSlug/auth-tokens'
      preLoaderRoute: typeof ApiOrgSlugAuthTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizations/$slug': {
      id: '/admin/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/admin/organizations/$slug'
      preLoaderRoute: typeof AdminOrganizationsSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$orgSlug/settings/profile': {
      id: '/$orgSlug/settings/profile'
      path: '/profile'
      fullPath: '/$orgSlug/settings/profile'
      preLoaderRoute: typeof OrgSlugSettingsProfileRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/$orgSlug/settings/organization': {
      id: '/$orgSlug/settings/organization'
      path: '/organization'
      fullPath: '/$orgSlug/settings/organization'
      preLoaderRoute: typeof OrgSlugSettingsOrganizationRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/api/cli/login/status': {
      id: '/api/cli/login/status'
      path: '/status'
      fullPath: '/api/cli/login/status'
      preLoaderRoute: typeof ApiCliLoginStatusRouteImport
      parentRoute: typeof ApiCliLoginRoute
    }
    '/api/admin/organizations/$slug': {
      id: '/api/admin/organizations/$slug'
      path: '/$slug'
      fullPath: '/api/admin/organizations/$slug'
      preLoaderRoute: typeof ApiAdminOrganizationsSlugRouteImport
      parentRoute: typeof ApiAdminOrganizationsRoute
    }
    '/api/$orgSlug/requests/replay': {
      id: '/api/$orgSlug/requests/replay'
      path: '/replay'
      fullPath: '/api/$orgSlug/requests/replay'
      preLoaderRoute: typeof ApiOrgSlugRequestsReplayRouteImport
      parentRoute: typeof ApiOrgSlugRequestsRoute
    }
    '/api/$orgSlug/requests/capture': {
      id: '/api/$orgSlug/requests/capture'
      path: '/capture'
      fullPath: '/api/$orgSlug/requests/capture'
      preLoaderRoute: typeof ApiOrgSlugRequestsCaptureRouteImport
      parentRoute: typeof ApiOrgSlugRequestsRoute
    }
    '/api/$orgSlug/portal/polar': {
      id: '/api/$orgSlug/portal/polar'
      path: '/api/$orgSlug/portal/polar'
      fullPath: '/api/$orgSlug/portal/polar'
      preLoaderRoute: typeof ApiOrgSlugPortalPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrgSlugSettingsRouteChildren {
  OrgSlugSettingsOrganizationRoute: typeof OrgSlugSettingsOrganizationRoute
  OrgSlugSettingsProfileRoute: typeof OrgSlugSettingsProfileRoute
  OrgSlugSettingsIndexRoute: typeof OrgSlugSettingsIndexRoute
}

const OrgSlugSettingsRouteChildren: OrgSlugSettingsRouteChildren = {
  OrgSlugSettingsOrganizationRoute: OrgSlugSettingsOrganizationRoute,
  OrgSlugSettingsProfileRoute: OrgSlugSettingsProfileRoute,
  OrgSlugSettingsIndexRoute: OrgSlugSettingsIndexRoute,
}

const OrgSlugSettingsRouteWithChildren = OrgSlugSettingsRoute._addFileChildren(
  OrgSlugSettingsRouteChildren,
)

interface OrgSlugRouteChildren {
  OrgSlugBillingRoute: typeof OrgSlugBillingRoute
  OrgSlugFirewallRoute: typeof OrgSlugFirewallRoute
  OrgSlugInstallRoute: typeof OrgSlugInstallRoute
  OrgSlugMembersRoute: typeof OrgSlugMembersRoute
  OrgSlugRequestsRoute: typeof OrgSlugRequestsRoute
  OrgSlugSettingsRoute: typeof OrgSlugSettingsRouteWithChildren
  OrgSlugTokensRoute: typeof OrgSlugTokensRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
}

const OrgSlugRouteChildren: OrgSlugRouteChildren = {
  OrgSlugBillingRoute: OrgSlugBillingRoute,
  OrgSlugFirewallRoute: OrgSlugFirewallRoute,
  OrgSlugInstallRoute: OrgSlugInstallRoute,
  OrgSlugMembersRoute: OrgSlugMembersRoute,
  OrgSlugRequestsRoute: OrgSlugRequestsRoute,
  OrgSlugSettingsRoute: OrgSlugSettingsRouteWithChildren,
  OrgSlugTokensRoute: OrgSlugTokensRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
}

const OrgSlugRouteWithChildren =
  OrgSlugRoute._addFileChildren(OrgSlugRouteChildren)

interface AdminRouteChildren {
  AdminChartsRoute: typeof AdminChartsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminOrganizationsSlugRoute: typeof AdminOrganizationsSlugRoute
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChartsRoute: AdminChartsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminOrganizationsSlugRoute: AdminOrganizationsSlugRoute,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiOrgSlugRequestsRouteChildren {
  ApiOrgSlugRequestsCaptureRoute: typeof ApiOrgSlugRequestsCaptureRoute
  ApiOrgSlugRequestsReplayRoute: typeof ApiOrgSlugRequestsReplayRoute
}

const ApiOrgSlugRequestsRouteChildren: ApiOrgSlugRequestsRouteChildren = {
  ApiOrgSlugRequestsCaptureRoute: ApiOrgSlugRequestsCaptureRoute,
  ApiOrgSlugRequestsReplayRoute: ApiOrgSlugRequestsReplayRoute,
}

const ApiOrgSlugRequestsRouteWithChildren =
  ApiOrgSlugRequestsRoute._addFileChildren(ApiOrgSlugRequestsRouteChildren)

interface ApiAdminOrganizationsRouteChildren {
  ApiAdminOrganizationsSlugRoute: typeof ApiAdminOrganizationsSlugRoute
}

const ApiAdminOrganizationsRouteChildren: ApiAdminOrganizationsRouteChildren = {
  ApiAdminOrganizationsSlugRoute: ApiAdminOrganizationsSlugRoute,
}

const ApiAdminOrganizationsRouteWithChildren =
  ApiAdminOrganizationsRoute._addFileChildren(
    ApiAdminOrganizationsRouteChildren,
  )

interface ApiCliLoginRouteChildren {
  ApiCliLoginStatusRoute: typeof ApiCliLoginStatusRoute
}

const ApiCliLoginRouteChildren: ApiCliLoginRouteChildren = {
  ApiCliLoginStatusRoute: ApiCliLoginStatusRoute,
}

const ApiCliLoginRouteWithChildren = ApiCliLoginRoute._addFileChildren(
  ApiCliLoginRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRoute: OrgSlugRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  EmailTemplatesRoute: EmailTemplatesRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  SelectRoute: SelectRoute,
  SignupRoute: SignupRoute,
  ApiSearchRoute: ApiSearchRoute,
  CliLoginRoute: CliLoginRoute,
  DocsSplatRoute: DocsSplatRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  ApiOrgSlugAuthTokensRoute: ApiOrgSlugAuthTokensRoute,
  ApiOrgSlugRequestsRoute: ApiOrgSlugRequestsRouteWithChildren,
  ApiOrgSlugSettingsRoute: ApiOrgSlugSettingsRoute,
  ApiOrgSlugSubscriptionsRoute: ApiOrgSlugSubscriptionsRoute,
  ApiAdminChartsRoute: ApiAdminChartsRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminOrganizationsRoute: ApiAdminOrganizationsRouteWithChildren,
  ApiAdminOverviewRoute: ApiAdminOverviewRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminSubscriptionsRoute: ApiAdminSubscriptionsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCheckoutPolarRoute: ApiCheckoutPolarRoute,
  ApiCliCompleteRoute: ApiCliCompleteRoute,
  ApiCliExchangeRoute: ApiCliExchangeRoute,
  ApiCliLoginRoute: ApiCliLoginRouteWithChildren,
  ApiDashboardValidateWsTokenRoute: ApiDashboardValidateWsTokenRoute,
  ApiDashboardWsTokenRoute: ApiDashboardWsTokenRoute,
  ApiMeOrgsRoute: ApiMeOrgsRoute,
  ApiOrganizationsCheckSlugRoute: ApiOrganizationsCheckSlugRoute,
  ApiSubscriptionsOrganizationIdRoute: ApiSubscriptionsOrganizationIdRoute,
  ApiWebhooksPolarRoute: ApiWebhooksPolarRoute,
  ApiOrgSlugPortalPolarRoute: ApiOrgSlugPortalPolarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
