import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
	docsSidebar: [
		'overview',
		{
			type: 'category',
			label: 'Client Integration Guide',
			items: [{ type: 'autogenerated', dirName: 'client-integration' }],
		},
		{
			type: 'category',
			label: 'Getting Started',
			items: [{ type: 'autogenerated', dirName: 'getting-started' }],
		},
		{
			type: 'category',
			label: 'Settings & Policies',
			items: [{ type: 'autogenerated', dirName: 'configuration' }],
		},
		{
			type: 'category',
			label: 'API',
			items: [{ type: 'autogenerated', dirName: 'api' }],
		},
		'api-reference',
		{
			type: 'category',
			label: 'Features',
			items: [{ type: 'autogenerated', dirName: 'features' }],
		},
		{
			type: 'category',
			label: 'Integrations',
			items: [{ type: 'autogenerated', dirName: 'integrations' }],
		},
		{
			type: 'category',
			label: 'Best Practices',
			items: [{ type: 'autogenerated', dirName: 'best-practices' }],
		},
		{
			type: 'category',
			label: 'Compliance',
			items: [{ type: 'autogenerated', dirName: 'compliance' }],
		},
		{
			type: 'category',
			label: 'Case Studies',
			items: [{ type: 'autogenerated', dirName: 'case-studies' }],
		},
	],
};

export default sidebars;
