import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar - autogenerated from the docs folder
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // generate sidebar from the docs folder
    },
  ],

  // You can also create custom sidebars for specific sections
  // Example:
  /*
  apiSidebar: [
    {
      type: 'category',
      label: 'API Reference',
      items: [
        { type: 'autogenerated', dirName: 'api' }
      ],
    },
  ],
  */
};

export default sidebars;
