"""add request logs

Revision ID: 118b09c33ba4
Revises: 003_add_api_keys_table
Create Date: 2026-02-11 20:20:15.490768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '118b09c33ba4'
down_revision = '003_add_api_keys_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_category', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('requires_retention', sa.Boolean(), nullable=True),
    sa.Column('compliance_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_category', 'tenant_audit_logs', ['tenant_id', 'event_category'], unique=False)
    op.create_index('idx_audit_event_type', 'tenant_audit_logs', ['tenant_id', 'event_type'], unique=False)
    op.create_index('idx_audit_severity', 'tenant_audit_logs', ['tenant_id', 'severity'], unique=False)
    op.create_index('idx_audit_tenant_timestamp', 'tenant_audit_logs', ['tenant_id', 'timestamp'], unique=False)
    op.create_table('tenant_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('config_key', sa.String(length=255), nullable=False),
    sa.Column('config_value', sa.JSON(), nullable=False),
    sa.Column('config_type', sa.String(length=50), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_config_key', 'tenant_configurations', ['tenant_id', 'config_key'], unique=False)
    op.create_index('idx_tenant_config_type', 'tenant_configurations', ['tenant_id', 'config_type'], unique=False)
    op.create_table('tenant_resource_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resource_usage_tenant_period', 'tenant_resource_usage', ['tenant_id', 'resource_type', 'period_start', 'period_end'], unique=False)
    op.create_table('request_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('tokens_prompt', sa.Integer(), nullable=True),
    sa.Column('tokens_completion', sa.Integer(), nullable=True),
    sa.Column('tokens_total', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('block_reason', sa.String(length=255), nullable=True),
    sa.Column('attack_detected', sa.Boolean(), nullable=True),
    sa.Column('attack_type', sa.String(length=50), nullable=True),
    sa.Column('attack_details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_api_key_id'), 'request_logs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_request_logs_attack_detected'), 'request_logs', ['attack_detected'], unique=False)
    op.create_index(op.f('ix_request_logs_is_blocked'), 'request_logs', ['is_blocked'], unique=False)
    op.create_index(op.f('ix_request_logs_provider'), 'request_logs', ['provider'], unique=False)
    op.create_index(op.f('ix_request_logs_request_id'), 'request_logs', ['request_id'], unique=True)
    op.create_index(op.f('ix_request_logs_timestamp'), 'request_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_request_logs_user_id'), 'request_logs', ['user_id'], unique=False)
    op.drop_index(op.f('idx_tenant_usage_period'), table_name='tenant_usage')
    op.drop_index(op.f('idx_tenant_usage_tenant_id'), table_name='tenant_usage')
    op.drop_table('tenant_usage')
    op.drop_index(op.f('idx_tenant_quotas_resource_type'), table_name='tenant_quotas')
    op.drop_index(op.f('idx_tenant_quotas_tenant_id'), table_name='tenant_quotas')
    op.drop_table('tenant_quotas')
    op.drop_constraint(op.f('api_keys_key_hash_key'), 'api_keys', type_='unique')
    op.drop_index(op.f('idx_api_keys_is_revoked'), table_name='api_keys')
    op.drop_index(op.f('idx_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('idx_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('idx_api_keys_user_id'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.add_column('tenant_api_keys', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tenant_api_keys', sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('tenant_api_keys', sa.Column('allowed_endpoints', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('tenant_api_keys', sa.Column('rate_limit_override', sa.Integer(), nullable=True))
    op.add_column('tenant_api_keys', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('tenant_api_keys', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('tenant_api_keys', 'key_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('tenant_api_keys', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('tenant_api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('tenant_api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_tenant_api_keys_key_hash'), table_name='tenant_api_keys')
    op.drop_index(op.f('idx_tenant_api_keys_tenant_id'), table_name='tenant_api_keys')
    op.create_index('idx_api_key_hash', 'tenant_api_keys', ['key_hash'], unique=False)
    op.create_index('idx_api_key_tenant', 'tenant_api_keys', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('tenant_api_keys_tenant_id_fkey'), 'tenant_api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_api_keys', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('tenant_api_keys', 'scopes')
    op.add_column('tenants', sa.Column('tenant_id', sa.String(length=50), nullable=False))
    op.add_column('tenants', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('subscription_id', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('encryption_key_hash', sa.String(length=128), nullable=True))
    op.add_column('tenants', sa.Column('max_requests_per_minute', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('max_requests_per_hour', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('max_requests_per_day', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('max_tokens_per_minute', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('max_tokens_per_hour', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('max_storage_bytes', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('max_active_sessions', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('audit_retention_days', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('compliance_requirements', sa.JSON(), nullable=True))
    op.add_column('tenants', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    op.alter_column('tenants', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('tenants', 'tier',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('tenants', 'api_key_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('idx_tenants_status'), table_name='tenants')
    op.drop_index(op.f('idx_tenants_tier'), table_name='tenants')
    op.drop_constraint(op.f('tenants_slug_key'), 'tenants', type_='unique')
    op.create_index('idx_tenant_created', 'tenants', ['created_at'], unique=False)
    op.create_index('idx_tenant_status', 'tenants', ['status'], unique=False)
    op.create_index('idx_tenant_tier', 'tenants', ['tier'], unique=False)
    op.create_index(op.f('ix_tenants_tenant_id'), 'tenants', ['tenant_id'], unique=True)
    op.drop_column('tenants', 'allowed_ips')
    op.drop_column('tenants', 'subscription_expires_at')
    op.drop_column('tenants', 'metadata')
    op.drop_column('tenants', 'webhook_url')
    op.drop_column('tenants', 'config')
    op.drop_column('tenants', 'webhook_secret')
    op.drop_column('tenants', 'slug')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_email_verification_token'), table_name='users')
    op.drop_index(op.f('idx_users_reset_password_token'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_index(op.f('idx_users_status'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email_verification_token'), 'users', ['email_verification_token'], unique=False)
    op.create_index(op.f('ix_users_reset_password_token'), 'users', ['reset_password_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_password_token'), table_name='users')
    op.drop_index(op.f('ix_users_email_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_reset_password_token'), 'users', ['reset_password_token'], unique=False)
    op.create_index(op.f('idx_users_email_verification_token'), 'users', ['email_verification_token'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.add_column('tenants', sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('webhook_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('webhook_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('subscription_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('allowed_ips', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tenants_tenant_id'), table_name='tenants')
    op.drop_index('idx_tenant_tier', table_name='tenants')
    op.drop_index('idx_tenant_status', table_name='tenants')
    op.drop_index('idx_tenant_created', table_name='tenants')
    op.create_unique_constraint(op.f('tenants_slug_key'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_tenants_tier'), 'tenants', ['tier'], unique=False)
    op.create_index(op.f('idx_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_index(op.f('idx_tenants_slug'), 'tenants', ['slug'], unique=False)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'api_key_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tenants', 'tier',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('tenants', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_column('tenants', 'deactivated_at')
    op.drop_column('tenants', 'created_by')
    op.drop_column('tenants', 'compliance_requirements')
    op.drop_column('tenants', 'audit_retention_days')
    op.drop_column('tenants', 'max_active_sessions')
    op.drop_column('tenants', 'max_storage_bytes')
    op.drop_column('tenants', 'max_tokens_per_hour')
    op.drop_column('tenants', 'max_tokens_per_minute')
    op.drop_column('tenants', 'max_requests_per_day')
    op.drop_column('tenants', 'max_requests_per_hour')
    op.drop_column('tenants', 'max_requests_per_minute')
    op.drop_column('tenants', 'encryption_key_hash')
    op.drop_column('tenants', 'subscription_id')
    op.drop_column('tenants', 'description')
    op.drop_column('tenants', 'tenant_id')
    op.add_column('tenant_api_keys', sa.Column('scopes', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tenant_api_keys', type_='foreignkey')
    op.create_foreign_key(op.f('tenant_api_keys_tenant_id_fkey'), 'tenant_api_keys', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_api_key_tenant', table_name='tenant_api_keys')
    op.drop_index('idx_api_key_hash', table_name='tenant_api_keys')
    op.create_index(op.f('idx_tenant_api_keys_tenant_id'), 'tenant_api_keys', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_tenant_api_keys_key_hash'), 'tenant_api_keys', ['key_hash'], unique=False)
    op.alter_column('tenant_api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenant_api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('tenant_api_keys', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('tenant_api_keys', 'key_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('tenant_api_keys', 'updated_at')
    op.drop_column('tenant_api_keys', 'created_by')
    op.drop_column('tenant_api_keys', 'rate_limit_override')
    op.drop_column('tenant_api_keys', 'allowed_endpoints')
    op.drop_column('tenant_api_keys', 'permissions')
    op.drop_column('tenant_api_keys', 'description')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index(op.f('idx_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('idx_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('idx_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_index(op.f('idx_api_keys_is_revoked'), 'api_keys', ['is_revoked'], unique=False)
    op.create_unique_constraint(op.f('api_keys_key_hash_key'), 'api_keys', ['key_hash'], postgresql_nulls_not_distinct=False)
    op.create_table('tenant_quotas',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('limit_value', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('current_value', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=True),
    sa.Column('reset_period', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_reset_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('tenant_quotas_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tenant_quotas_pkey'))
    )
    op.create_index(op.f('idx_tenant_quotas_tenant_id'), 'tenant_quotas', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_tenant_quotas_resource_type'), 'tenant_quotas', ['resource_type'], unique=False)
    op.create_table('tenant_usage',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('requests_total', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('requests_blocked', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('tokens_processed', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=True),
    sa.Column('storage_bytes', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('tenant_usage_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tenant_usage_pkey'))
    )
    op.create_index(op.f('idx_tenant_usage_tenant_id'), 'tenant_usage', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_tenant_usage_period'), 'tenant_usage', ['period_start', 'period_end'], unique=False)
    op.drop_index(op.f('ix_request_logs_user_id'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_timestamp'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_request_id'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_provider'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_is_blocked'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_attack_detected'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_api_key_id'), table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_index('idx_resource_usage_tenant_period', table_name='tenant_resource_usage')
    op.drop_table('tenant_resource_usage')
    op.drop_index('idx_tenant_config_type', table_name='tenant_configurations')
    op.drop_index('idx_tenant_config_key', table_name='tenant_configurations')
    op.drop_table('tenant_configurations')
    op.drop_index('idx_audit_tenant_timestamp', table_name='tenant_audit_logs')
    op.drop_index('idx_audit_severity', table_name='tenant_audit_logs')
    op.drop_index('idx_audit_event_type', table_name='tenant_audit_logs')
    op.drop_index('idx_audit_category', table_name='tenant_audit_logs')
    op.drop_table('tenant_audit_logs')
    # ### end Alembic commands ###
